### ISSUE TITLE
s2 tests all pass straight away

### ISSUE THREAD

**Issue by samjam48** [foundersandcoders/ws-software-design-js#35]
the tests for the second project were all passing when I ran the test file before I started the exercise and the same for my partner

**Comment by gminova** [comment]
in the top comment it exercise.js says:
 Exercise: Create some modules!
 *
 * When you think you have finished, run the command:
 *   npm run s2.module
 * This will run a series of tests which should all pass.
 */

**Comment by samjam48** [comment]
Some key points on the semantics of what they are saying.

_"When you think you have **finished**...
This will run a series of tests which **should** all pass"_

I think this means that once you have finished coding and you expect that your function works. You can run the tests and if they work, then the tests will pass.

If all the tests pass when your function is wrong (my partner's function was wrong) then the test isn't testing it properly.


**The Issue** 🔍 

Looked at the actual problem instead of just talking about it.

![image](https://user-images.githubusercontent.com/16625180/61309393-cdec7880-a7fa-11e9-855d-1a267d53f49c.png)

The tests page is testing the solutions.js and it isn't testing the exercise.js 🙈 

Either this needs to be mentioned in the README so students know that the test currently isn't testing their code. Or we just change the test file to test the students code instead of the solutions code.

**Comment by samjam48** [comment]
Turns out there is a pull request to fix exactly this but there is something wrong with it so should be restarted.

Is there a procedure around doing this? I'm a bit out of the loop here in Israel 🇮🇱
