### ISSUE TITLE
needs AUTHOR.md

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-software-design-js#5]
Option 2 (active maintainer) @eliascodes 

Ideally we would use the same format across all repos in `foundersandcoders`

---

# Author
**Active maintainer**
--insert name--
--insert github handle-- (so students know who to @ when they want to raise issues and assign PRs)
--insert photo of author--  (because of https://github.com/foundersandcoders/london-programme/issues/223)

---

I was going to use the photos that FAC has of us from day 1 of the course. But obviously people would be free to update it with any photo of themselves that they wanted

**Comment by eliasmalik** [comment]
@jsms90 surely easier to just link to my profile page: there's a picture there.

**Comment by jsms90** [comment]
+ Not everyone's profiles have a picture that helps you to know who they are. This is specifically to tie a face to a name / github handle, especially given foundersandcoders/london-programme#223 has been repeated across cohorts
+ A name is nice to know, or you end up referring to people, in person, as @des-des or "Hilbert" (i.e. Joudy at the curriculum meeting) :rofl:
+ The github handle could link to their profile? :+1:

**Comment by njsfield** [comment]
@jsms90 Rather than bloating a repo with image files (and requesting additional pics of people), just remind them their profiles are being linked in their AUTHOR.md file, so ensure their GitHub profile includes their name & pic.

Clearly the issue is people's profiles, not missing content from author files.

**Comment by jsms90** [comment]
Good point about bloating with a photo :thinking: 

I don't think we can make people do anything with their own profiles. If people want something more artistic, rather than a recognisable picture of them, that's up to them :woman_shrugging:. Whereas, in FAC materials, it seemed like a reasonable place to request clarity.

But I think you're right, and this is probably unnecessary extra admin. What you _need_ is a github handle.

So maybe no `AUTHOR.md`? Seems excessive for nothing but a github handle. Maybe just at the top of the `README.md` itself?

How about:

---

**Author:** [@njsfield](https://github.com/njsfield/)
**Maintainer:** [@njsfield](https://github.com/njsfield/)

Workshop begins here
